define schema DCM_PROJECT_{{db}}.ANALYTICS;

define dynamic table DCM_PROJECT_{{db}}.ANALYTICS.V_ENRICHED_ORDER_DETAILS
warehouse = DCM_PROJECT_WH_{{db}}
target_lag = '12 hours'
as
select
    oh.ORDER_ID,
    oh.ORDER_TS,
    od.QUANTITY,
    m.MENU_ITEM_NAME,
    m.ITEM_CATEGORY,
    m.SALE_PRICE_USD,
    m.COST_OF_GOODS_USD,
    (od.QUANTITY * m.SALE_PRICE_USD) AS LINE_ITEM_REVENUE,
    (od.QUANTITY * (m.SALE_PRICE_USD - m.COST_OF_GOODS_USD)) AS LINE_ITEM_PROFIT,
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.CITY AS CUSTOMER_CITY,
    t.TRUCK_ID,
    t.TRUCK_BRAND_NAME
from
    DCM_PROJECT_{{db}}.RAW.ORDER_HEADER oh
join
    DCM_PROJECT_{{db}}.RAW.ORDER_DETAIL od
    on oh.ORDER_ID = od.ORDER_ID
join
    DCM_PROJECT_{{db}}.RAW.MENU m
    ON od.MENU_ITEM_ID = m.MENU_ITEM_ID
join
    DCM_PROJECT_{{db}}.RAW.CUSTOMER c
    ON oh.CUSTOMER_ID = c.CUSTOMER_ID
join
    DCM_PROJECT_{{db}}.RAW.TRUCK t
    ON oh.TRUCK_ID = t.TRUCK_ID
;


define dynamic table DCM_PROJECT_{{db}}.ANALYTICS.V_MENU_ITEM_POPULARITY
warehouse = DCM_PROJECT_WH_{{db}}
target_lag = '12 hours'
as
select
    MENU_ITEM_NAME,
    ITEM_CATEGORY,
    COUNT(DISTINCT ORDER_ID) AS NUMBER_OF_ORDERS,
    SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(LINE_ITEM_REVENUE) AS TOTAL_REVENUE
FROM
    DCM_PROJECT_{{db}}.ANALYTICS.V_ENRICHED_ORDER_DETAILS
GROUP BY
    MENU_ITEM_NAME, ITEM_CATEGORY
ORDER BY
    TOTAL_REVENUE DESC
;


define dynamic table DCM_PROJECT_{{db}}.ANALYTICS.V_CUSTOMER_SPENDING_SUMMARY
warehouse = DCM_PROJECT_WH_{{db}}
target_lag = '12 hours'
as
select
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    CUSTOMER_CITY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(LINE_ITEM_REVENUE) AS TOTAL_SPEND_USD,
    MIN(ORDER_TS) AS FIRST_ORDER_DATE,
    MAX(ORDER_TS) AS LATEST_ORDER_DATE
FROM
    DCM_PROJECT_{{db}}.ANALYTICS.V_ENRICHED_ORDER_DETAILS
GROUP BY
    CUSTOMER_ID, FIRST_NAME, LAST_NAME, CUSTOMER_CITY
ORDER BY
    TOTAL_SPEND_USD DESC
;


define dynamic table DCM_PROJECT_{{db}}.ANALYTICS.V_TRUCK_PERFORMANCE
warehouse = DCM_PROJECT_WH_{{db}}
target_lag = '12 hours'
as
select
    TRUCK_BRAND_NAME,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(LINE_ITEM_REVENUE) AS TOTAL_REVENUE,
    SUM(LINE_ITEM_PROFIT) AS TOTAL_PROFIT
FROM
    DCM_PROJECT_{{db}}.ANALYTICS.V_ENRICHED_ORDER_DETAILS
GROUP BY
    TRUCK_BRAND_NAME
ORDER BY
    TOTAL_REVENUE DESC
;
