point_of_contact: "@snowflakedb/snowcli"
production: true
distributed: true
modified: false
code_owners_file_present: true
release_branches:
  - main
jira_area: Developer Platform
audit_in_scope: true
