name: Render all templates

on:
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  render_templates:
    name: Render templates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Snowflake CLI
        run: python -m pip install git+https://github.com/snowflakedb/snowflake-cli.git@932adb508f2be468da234fa0423244a27de99662
      - name: Render all templates
        run: python .github/workflows/scripts/render_all_templates.py .
