name: Run tests

on:
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        cli_version: ['==2.7.0', '==2.8.0', ''] # check 2.X and latest release
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Snowflake CLI
        run: python -m pip install pytest snowflake-snowpark-python snowflake-cli${{ matrix.cli_version }}
      - name: Run tests
        run: python -m pytest .tests/ -vv
